/**
 * Generation mode-vakterna (AI-spec §32, konstitutionen §25): deterministisk
 * efterkontroll av VARJE textförslag innan det får visas för sökanden. Det är
 * vakterna — inte språkmodellen — som bär garantierna:
 *
 *  - INVENTED_NUMBER: förslaget får inte innehålla en siffra som inte fanns i
 *    sökandens egen text. En modell som "förbättrar" med nya tal avvisas
 *    maskinellt — hallucination stoppas i grinden, inte i policyn.
 *  - META_TRACE: inga verktygs-/AI-spår (§4 no meta-trace).
 *  - INTRODUCED_LANGUAGE_RISK: förslaget får inte INFÖRA superlativ,
 *    standardfraser eller utfallslöften som inte redan fanns (§12–13, §21).
 *  - RUNAWAY_LENGTH: förslaget får inte svälla — kvalitet är inte längd (§21).
 *
 * Ett avvisat förslag visas aldrig. Ett godkänt förslag är fortfarande bara
 * ett FÖRSLAG — sökanden godkänner varje formulering själv (§3, §30).
 */
import { humilityFindings } from './language.js';

export interface GuardFinding {
  kind: 'INVENTED_NUMBER' | 'META_TRACE' | 'INTRODUCED_LANGUAGE_RISK' | 'RUNAWAY_LENGTH';
  detail: string;
}

export interface GuardVerdict {
  passed: boolean;
  findings: GuardFinding[];
}

const META_MARKERS = ['Bidragskoll.se', 'bidragskoll.se', ' AI ', 'genererad', 'generated by', 'optimized', 'INTERNAL_ESTIMATE', 'prompt'];

export function generationGuards(before: string, suggestion: string): GuardVerdict {
  const findings: GuardFinding[] = [];

  // Siffervakten: varje sifferrun i förslaget måste finnas i originalet.
  const beforeNumbers = new Set(before.match(/\d+/g) ?? []);
  for (const n of new Set(suggestion.match(/\d+/g) ?? [])) {
    if (!beforeNumbers.has(n)) findings.push({ kind: 'INVENTED_NUMBER', detail: n });
  }

  for (const marker of META_MARKERS) {
    if (suggestion.includes(marker)) findings.push({ kind: 'META_TRACE', detail: marker.trim() });
  }

  // Språkrisker som INFÖRS av förslaget (fanns de redan är de sökandens val
  // och flaggas av den vanliga språkkontrollen, inte av vakten).
  const beforeTerms = new Set(humilityFindings(before).map((f) => f.term.toLowerCase()));
  for (const f of humilityFindings(suggestion)) {
    if (!beforeTerms.has(f.term.toLowerCase())) {
      findings.push({ kind: 'INTRODUCED_LANGUAGE_RISK', detail: f.term });
    }
  }

  if (suggestion.length > Math.max(400, before.length * 2)) {
    findings.push({ kind: 'RUNAWAY_LENGTH', detail: `${suggestion.length} tecken mot originalets ${before.length}` });
  }

  return { passed: findings.length === 0, findings };
}
